### PR TITLE
Make spec-coerce an optional dependency

### PR DESCRIPTION
**Pull request by thumbnail**
## Brief

✨ Discussion piece ✨ 

spec-coerce isn't a common dependency for us, so i'd like to make it optional. Either by excluding the dependency in consumers (opt-out) or adding the dependency by consumers who want to use it (opt-in) or removing it altogether. In this PR i make `coerce-map-indicating-invalidity` opt-in.

Alternative 1: keep `spec-coerce` in `project.clj` and exclude in consumers (made possible by the 'requiring-resolve'-call).
Alternative 2: Remove function, bump major to 2.0.0

context: 
 - also `components.pedestal` uses spec-coerce: https://github.com/nedap/components.pedestal/blob/c4faad869634eaeab12a82a264cf2cb0a6ed6e76/src/nedap/components/pedestal/interceptors/spec_coercer.clj#L14
 - `utils.spec.predicates` extends spec-coerse: https://github.com/nedap/utils.spec.predicates/blob/da4a1216788e50c5aa5aa894127648c0c2a42bd3/src/nedap/utils/spec/predicates.cljc#L89-L94

WDYT @nedap/sts-clojure-dev ?

## Author checklist

* [ ] I have QAed the functionality
* [ ] The PR has a reasonably reviewable size and a meaningful commit history
* [ ] I have run the [branch formatter](https://github.com/nedap/formatting-stack/blob/332a419034ab46fad526a5592f4257353bd695b6/src/formatting_stack/branch_formatter.clj) and observed no new/significative warnings
* [ ] The build passes
* [ ] I have self-reviewed the PR prior to assignment
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Modular design
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

## Reviewer checklist

* [ ] I have checked out this branch and reviewed it locally, running it
* [ ] I have QAed the functionality
* [ ] I have reviewed the PR
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Modular design
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

### CODE REVIEW

**Comment by thumbnail** [comment]
Given that the cljs testsuite broke, a major bump and removing the function all-together may be the path of least resistance.

**Comment by vemv** [comment]
Perhaps this would work?

```clj
;; defined in a separate .clj file
(defmacro when-spec-coerce-available [& body]
  (when (try
          (require 'spec-coerce.core)
          true
          (catch Exception _
            false))
    (do
      ~@body)))

;; no reader conditional needed
(when-spec-coerce-available
  (defn coerce-map-indicating-invalidity ,,,))
```

Then you'd remove the `require`s entirely (because there are no conditional requires in cljs) - it would become up to the consumers to 1) provide the dep, and 2) declare the requires

**Comment by thumbnail** [comment]
> because there are no conditional requires in cljs

I thought this was fixed (https://anmonteiro.com/2016/10/clojurescript-require-outside-ns/) but with little cljs experience i'm probably mistaken.


Regarding the `when-spec-coerce-available`, we do a similar thing in f-s, https://github.com/nedap/formatting-stack/blob/541ffcf6341735a63ca451d4d8782f2feaf7aacb/src/formatting_stack/strategies.clj#L211-L228

It could even be a function, I think 🤔.

But this would still be a breaking change (consumers are forced to change their usage by adding a dep + require).

**Comment by vemv** [comment]
> I thought this was fixed (https://anmonteiro.com/2016/10/clojurescript-require-outside-ns/)

It works only in the repl or similar environments, AFAIK

> But this would still be a breaking change

Some breaking changes are better than others :) one has a migration path, the other not. It seems to play well with semver + a changelog

**Comment by thumbnail** [comment]
> one has a migration path, the other not

IMO the migration paths are similar. Adding the require + dependency to your `project.clj` vs moving the function into your project.

From what I can see in the github search / grep.app there's no (public!) usage of this fn anyway. Removing it likely has very little impact whichever option we pick.

**Comment by vemv** [comment]
I like using the affected fn for quick web projects

**Review by neominik — APPROVED** [review]

**Pull request merged**
